import test from 'node:test';
import assert from 'node:assert/strict';
import { candidateDataset } from '../src/content/candidate-v01.js';
import { validateDataset,ContentError,allEntities,validDate,validSlug } from '../src/editorial/validate.js';
import { createCore,visible,contextFor } from '../src/editorial/core.js';
import type { Dataset } from '../src/editorial/contracts.js';
const now='2026-09-14T12:00:00Z';
const fixture=()=>structuredClone(candidateDataset);
const publicFixture=()=>{const d=fixture();d.site.reviewState='accepted';for(const e of allEntities(d)){e.reviewState='accepted';e.publicationState='published';e.publishedAt=e.updatedAt;}return d;};
function invalid(name:string,mutate:(d:Dataset)=>void,code?:string){test(name,()=>{const d=fixture();mutate(d);assert.throws(()=>validateDataset(d),(err:unknown)=>err instanceof ContentError&&(!code||err.problems.some(p=>p.code===code)));});}
test('fixture validates without input mutation',()=>{const d=fixture(),before=structuredClone(d);validateDataset(d);assert.deepEqual(d,before);});
test('normalization is idempotent',()=>{const d=validateDataset(fixture());assert.deepEqual(validateDataset(d),d);});
test('eight entity types present',()=>assert.equal(new Set(allEntities(fixture()).map(e=>e.kind)).size,8));
invalid('empty title rejected',d=>d.articles[0].title=' ');
invalid('wrong id prefix rejected',d=>(d.articles[0] as any).id='scent:a001');
invalid('unknown state rejected',d=>(d.articles[0] as any).publicationState='live');
invalid('extra private field rejected',d=>(d.articles[0] as any).privateContext='not allowed');
invalid('invalid revision rejected',d=>d.articles[0].revision=0);
invalid('duplicate id rejected',d=>d.articles.push(structuredClone(d.articles[0])),'DUPLICATE_ID');
invalid('duplicate slug rejected',d=>d.articles.push({...d.articles[0],id:'article:a002'}),'DUPLICATE');
invalid('duplicate issue article rejected',d=>d.issues[0].articleIds.push('article:a001'),'DUPLICATE');
invalid('broken relation rejected',d=>d.articles[0].primaryScentId='scent:missing','BROKEN_REFERENCE');
invalid('duplicate scent relation rejected',d=>d.articles[0].additionalScentIds=['scent:s001'],'DUPLICATE');
invalid('duplicate availability rejected',d=>d.availabilities.push({...d.availabilities[0],id:'availability:av002'}),'DUPLICATE');
invalid('ingredient needs documented evidence',d=>d.scents[0].materialLinks![0].relation='documented_ingredient','INGREDIENT_EVIDENCE_REQUIRED');
invalid('record needs documented evidence',d=>d.records[0].evidenceType='documented','RECORD_EVIDENCE_REQUIRED');
invalid('candidate cannot be published',d=>d.articles[0].publicationState='published','INVALID_PUBLICATION');
invalid('non-finite price rejected',d=>d.products[0].price={currency:'KRW',amount:Infinity});
invalid('negative volume rejected',d=>d.products[0].volumeMl=-1);
invalid('executable URL rejected',d=>d.articles[0].body.push({type:'external_link',href:'javascript:alert(1)',label:'bad'}));
invalid('duplicate block anchor rejected',d=>d.articles[0].body.push({type:'heading',level:2,anchor:'starting-point',text:'other'}),'DUPLICATE');
test('slug boundaries',()=>{assert.ok(validSlug('after-blue-sunset'));for(const s of ['Bad','a--b','/a','a?b','a#b','-a','a/..','a'.repeat(81)])assert.equal(validSlug(s),false);});
test('calendar dates validated',()=>{assert.ok(validDate('2024-02-29T00:00:00Z'));for(const s of ['2026-02-30T00:00:00Z','2026-01-01','2026-01-01T24:00:00Z'])assert.equal(validDate(s),false);});
test('public fixture loader candidate forbidden',()=>assert.throws(()=>createCore(fixture(),'public',now),/CANDIDATE_SITE/));
test('review includes draft while public excludes it',()=>{const e=fixture().articles[0];assert.ok(visible(e,'review',now));assert.equal(visible(e,'public',now),false);});
test('public required target cannot point to draft',()=>{const d=publicFixture();d.articles[0].publicationState='draft';assert.throws(()=>createCore(d,'public',now),/TARGET_NOT_PUBLIC/);});
test('illustrative record never public',()=>{const d=publicFixture();const s=createCore(d,'public',now).pages().find(p=>p.kind==='scent')!;assert.ok(!s.sections.some(s=>s.id==='record-r001'));});
test('future publication rejected',()=>{const d=publicFixture();d.issues[0].publishedAt='2027-01-01T00:00:00Z';d.issues[0].updatedAt=d.issues[0].publishedAt;assert.throws(()=>createCore(d,'public',now),/FUTURE_PUBLICATION/);});
test('five complete route pages',()=>assert.deepEqual(createCore(fixture(),'review',now).pages().map(p=>p.path).sort(),['/','/info/','/issues/unnamed-sensations/','/articles/what-remains/','/scents/after-blue-sunset/'].sort()));
test('article addition flows into issue',()=>{const d=fixture();d.articles.push({...d.articles[0],id:'article:a002',slug:'next-note',title:'Next candidate'});d.issues[0].articleIds.push('article:a002');const core=createCore(d,'review',now);assert.ok(core.pages().some(p=>p.path==='/articles/next-note/'));assert.equal(core.pages().find(p=>p.kind==='issue')!.sections[0].links!.length,2);});
test('invalid issue context ignored',()=>{const c=createCore(fixture(),'review',now).pages().find(p=>p.kind==='article')!.contexts!;assert.equal(contextFor(c,'invalid'),undefined);assert.equal(contextFor(c,null),undefined);assert.equal(contextFor(c,'unnamed-sensations')?.position,1);});
test('unknown availability with no record',()=>{const d=fixture();d.availabilities=[];assert.equal(createCore(d,'review',now).availability('product:p001').state,'unknown');});
test('candidate availability cannot claim available',()=>{const d=fixture();d.availabilities[0].state='available';assert.equal(createCore(d,'review',now).availability('product:p001').state,'unknown');});
test('manual availability interval and expiry',()=>{const d=fixture();Object.assign(d.availabilities[0],{source:'manual',reviewState:'accepted',state:'available',checkedAt:'2026-09-14T00:00:00Z',validUntil:'2026-09-15T00:00:00Z'});assert.equal(createCore(d,'review',now).availability('product:p001').state,'available');assert.equal(createCore(d,'review','2026-09-15T00:00:00Z').availability('product:p001').state,'unknown');});
test('missing interval means unknown',()=>{const d=fixture();Object.assign(d.availabilities[0],{source:'manual',reviewState:'accepted',state:'available'});assert.equal(createCore(d,'review',now).availability('product:p001').state,'unknown');});
test('unavailable product does not remove dossier',()=>{const d=fixture();Object.assign(d.availabilities[0],{source:'manual',reviewState:'accepted',state:'unavailable'});const c=createCore(d,'review',now);assert.ok(c.pages().some(p=>p.kind==='scent'));assert.equal(c.availability('product:p001').state,'unavailable');assert.equal(c.availability('product:p001').action.href,'/info/#samples');});
test('missing price is not zero price',()=>{const d=fixture();let pages=createCore(d,'review',now).pages();assert.ok(!JSON.stringify(pages).includes('0원'));d.products[0].price={currency:'KRW',amount:0};pages=createCore(d,'review',now).pages();assert.ok(JSON.stringify(pages).includes('0원'));});
test('all empty collections still yield home and info',()=>{const d=fixture();d.site.home.featuredIssueId=undefined;d.site.home.featuredScentId=undefined;d.issues=[];d.articles=[];d.scents=[];d.materials=[];d.objects=[];d.records=[];d.products=[];d.availabilities=[];const pages=createCore(d,'review',now).pages();assert.equal(pages.length,2);assert.ok(pages[0].sections.some(s=>s.id==='issues'));});
test('raw evidence and SKU do not leak into page views',()=>{const d=fixture();d.records[0].evidenceRef='private-reference';d.products[0].sku='private-sku';const output=JSON.stringify(createCore(d,'review',now).pages());assert.ok(!output.includes('private-reference'));assert.ok(!output.includes('private-sku'));});
test('published slugs may match across namespaces',()=>{const d=fixture();d.articles[0].slug=d.issues[0].slug;assert.doesNotThrow(()=>validateDataset(d));});
test('all generated internal links have page/anchor targets',()=>{const pages=createCore(fixture(),'review',now).pages();const routes=new Map(pages.map(p=>[p.path,p]));for(const page of pages){const ls=[...page.sections.flatMap(s=>s.links??[]),...(page.contexts??[]).flatMap(c=>c.links),...(page.blocks??[]).flatMap(b=>b.type==='link'?[b]:[])];for(const l of ls){if(!l.href.startsWith('/'))continue;const u=new URL(l.href,'https://review.invalid');const target=routes.get(u.pathname);assert.ok(target,l.href);if(u.hash)assert.ok(target.sections.some(s=>s.id===u.hash.slice(1)),l.href);}}});
